server {
    listen 80;
    server_name apidemo.local;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name apidemo.local;

    ssl_certificate     /etc/nginx/certs/apidemo.local.pem;
    ssl_certificate_key /etc/nginx/certs/apidemo.local-key.pem;

    root /var/www/html/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_param HTTPS on;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
